FROM node:20-alpine

# Set build arguments
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG CLERK_SECRET_KEY
ARG NEXT_PUBLIC_CLERK_SIGN_IN_URL
ARG NEXT_PUBLIC_CLERK_SIGN_UP_URL
ARG NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
ARG NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
ARG DATABASE_URL
ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ARG DOMAIN_URL
ARG REACT_APP_GEMINI_API_KEY
ARG MERCHANT_ID
ARG MERCHANT_SECRET
ARG NOTIFY_URL
ARG PUSHER_APP_ID
ARG PUSHER_APP_KEY
ARG PUSHER_SECRET
ARG PUSHER_CLUSTER

# Set environment variables
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV CLERK_SECRET_KEY=$CLERK_SECRET_KEY
ENV NEXT_PUBLIC_CLERK_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_SIGN_IN_URL
ENV NEXT_PUBLIC_CLERK_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_SIGN_UP_URL
ENV NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
ENV NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
ENV DATABASE_URL=$DATABASE_URL
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=$NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ENV DOMAIN_URL=$DOMAIN_URL
ENV REACT_APP_GEMINI_API_KEY=$REACT_APP_GEMINI_API_KEY
ENV MERCHANT_ID=$MERCHANT_ID
ENV MERCHANT_SECRET=$MERCHANT_SECRET
ENV NOTIFY_URL=$NOTIFY_URL
ENV PUSHER_APP_ID=$PUSHER_APP_ID
ENV PUSHER_APP_KEY=$PUSHER_APP_KEY
ENV PUSHER_SECRET=$PUSHER_SECRET
ENV PUSHER_CLUSTER=$PUSHER_CLUSTER

# Create app directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the app
COPY . .

# Build your application (if applicable)
RUN npm run build

# Expose the port
EXPOSE 3000

# Command to run your app
CMD ["npm", "start"]